[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
    hirotakaster/CoAP simple library @ ^1.3.24

build_flags =
    -D CORE_DEBUG_LEVEL=5

lib_ldf_mode = deep+
build_type = debug
